services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MAILGUN_API_KEY=${MAILGUN_API_KEY}
      - MAILGUN_DOMAIN=${MAILGUN_DOMAIN}
      - FROM_EMAIL=${FROM_EMAIL}
      - TO_EMAIL=${TO_EMAIL}
      - ORIGIN=https://www.morgantownfnb.org
    restart: unless-stopped
